=== CJSCommonPlatform/dependency-mapper/src/test/resources/microservice_project/src/raml/json/schema/progression.query.defendant.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "defendantProgressionId": {
      "type": "string"
    },
    "defendantId": {
      "type": "string"
    },
    "caseProgressionId": {
      "type": "string"
    },
    "sentenceHearingReviewDecision": {
      "type": "boolean"
    },
    "sentenceHearingReviewDecisionDateTime": {
      "type": "string"
    },
    "additionalInformation": {
      "type": "object",
      "properties": {
        "probation": {
          "type": "object",
          "properties": {
            "preSentenceReport": {
              "type": "object",
              "properties": {
                "psrIsRequested": {
                  "type": "boolean"
                },
                "provideGuidance": {
                  "type": "string"
                },
                "drugAssessment": {
                  "type": "boolean"
                }
              }
            },
            "dangerousnessAssessment": {
              "type": "boolean"
            }
          }
        },
        "defence": {
          "type": "object",
          "properties": {
            "statementOfMeans": {
              "type": "object",
              "properties": {
                "isStatementOfMeans": {
                  "type": "boolean"
                },
                "details": {
                  "type": "string"
                }
              }
            },
            "medicalDocumentation": {
              "type": "object",
              "properties": {
                "isMedicalDocumentation": {
                  "type": "boolean"
                },
                "details": {
                  "type": "string"
                }
              }
            },
            "otherDetails": {
              "type": "string"
            }
          }
        },
        "prosecution": {
          "type": "object",
          "properties": {
            "ancillaryOrders": {
              "type": "object",
              "properties": {
                "isAncillaryOrders": {
                  "type": "boolean"
                },
                "details": {
                  "type": "string"
                }
              }
            },
            "otherDetails": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "required": [
    "defendantProgressionId",
    "defendantId",
    "caseProgressionId",
    "sentenceHearingReviewDecision",
    "sentenceHearingReviewDecisionDateTime"
  ]
}

=== CJSCommonPlatform/dependency-mapper/src/test/resources/microservice_project/src/raml/json/progression.query.defendant.json
{
  "defendantProgressionId": "4daefec6-5f77-4109-82d9-1e60544a6c05",
  "defendantId": "3daefec6-5f77-4109-82d9-1e60544a6c12",
  "caseProgressionId": "3daefec6-5f77-4109-82d9-1e60544a6c10", 
  "sentenceHearingReviewDecision": false,
  "sentenceHearingReviewDecisionDateTime": "2016-01-01 20:12",
  "additionalInformation": {
    "probation": {
      "preSentenceReport": {
        "psrIsRequested": true,
        "provideGuidance": "guidance",
        "drugAssessment": true
      },
      "dangerousnessAssessment": true
    },
    "defence": {
      "statementOfMeans": {
        "isStatementOfMeans": true,
        "details": "meansDetails"
      },
      "medicalDocumentation": {
        "isMedicalDocumentation": true,
        "details": "medicalDetails"
      },
      "otherDetails": "otherDetails"
    },
    "prosecution": {
      "ancillaryOrders": {
        "isAncillaryOrders": true,
        "details": "ancillaryOrdersDetails"
      },
      "otherDetails": "otherDetails"
    }
  }
}
